name: .NET 8 WebAPI CI (Linux Runner + Linux App Service)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository so we have access to solution & projects
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) (Optional) Cache NuGet packages to speed up restores and builds
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # 3) Install .NET 8 SDK on Ubuntu
      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 4) Restore all dependencies for the solution at the repository root
      - name: Restore dependencies
        run: dotnet restore HealthHUB.API.sln

      # 5) Build the entire solution (no --output here)
      - name: Build solution
        run: dotnet build HealthHUB.API.sln --no-restore --configuration Release

      # 6) Run all unit tests in the solution
      - name: Run tests
        run: dotnet test HealthHUB.API.sln --no-build --verbosity normal

      # 7) Publish the HealthHUB.API project to the ./publish folder
      - name: Publish WebAPI
        run: dotnet publish HealthHUB.API/HealthHUB.API.csproj --configuration Release --output ./publish

      # 8) Deploy the published output to a Linux-based Azure App Service
      - name: Deploy to Azure Web App (Linux)
        uses: Azure/webapps-deploy@v2
        with:
          # Replace this with the exact name of your Linux App Service
          app-name: healthhub-api-demo  
          slot-name: Production
          # The publish profile (XML) you saved into GitHub Secrets as AZURE_WEBAPP_PUBLISH_PROFILE
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      # 9) (Optional) Upload the published folder as a GitHub Actions artifact
      - name: Upload build artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: webapi-published
          path: ./publish
